services:
  ssh:
    image: "${INMANTA_ORCHESTRATOR_IMAGE:?error}"
    container_name: inmanta-ssh-sidecar
    pull_policy: always
    entrypoint: ["/usr/bin/tini", "--", "/sshd-entrypoint.sh"]
    ports:
      - "${INMANTA_SSH_SIDECAR_IP:-127.0.0.1}:${INMANTA_SSH_SIDECAR_PORT:-2222}:22"
    environment:
      INMANTA_CMDLINE_REST_TRANSPORT_HOST: inmanta-orchestrator
      INMANTA_COMPILER_REST_TRANSPORT_HOST: inmanta-orchestrator
      INMANTA_CLIENT_REST_TRANSPORT_HOST: inmanta-orchestrator
      INMANTA_AUTHORIZED_KEYS: "${INMANTA_AUTHORIZED_KEYS}"
    user: "root:root"
    healthcheck:
      test: ["CMD-SHELL", "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null inmanta@127.0.0.1 true"]
      interval: 60s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./sshd-entrypoint.sh:/sshd-entrypoint.sh
      - inmanta-server-data:/var/lib/inmanta
      - inmanta-server-logs:/var/log/inmanta
