services:
  logrotate:
    image: "${INMANTA_ORCHESTRATOR_LOGROTATE_IMAGE:-ghcr.io/inmanta/orchestrator-logrotate:latest}"
    container_name: inmanta-logrotate-sidecar
    build:
      context: .
      dockerfile: logrotate.Dockerfile
      args:
        INMANTA_ORCHESTRATOR_IMAGE: "${INMANTA_ORCHESTRATOR_IMAGE:?error}"
    pull_policy: build
    volumes:
      - inmanta-server-logs:/var/log/inmanta
      - inmanta-logrotate-data:/var/lib/logrotate

volumes:
  inmanta-logrotate-data: {}
