services:
  code:
    image: "${INMANTA_ORCHESTRATOR_IMAGE:?error}"
    container_name: inmanta-code-sidecar
    pull_policy: always
    ports:
      - "${INMANTA_CODE_SERVER_IP:-127.0.0.1}:${INMANTA_CODE_SERVER_PORT:-8080}:8080"
    entrypoint: ["/usr/bin/tini", "--", "/code-entrypoint.sh"]
    environment:
      INMANTA_CMDLINE_REST_TRANSPORT_HOST: inmanta-orchestrator
      INMANTA_COMPILER_REST_TRANSPORT_HOST: inmanta-orchestrator
      INMANTA_CLIENT_REST_TRANSPORT_HOST: inmanta-orchestrator
    user: "root:root"
    volumes:
      - ./code-entrypoint.sh:/code-entrypoint.sh
      - inmanta-server-data:/var/lib/inmanta
      - inmanta-server-logs:/var/log/inmanta
