services:
  db:
    image: "docker.io/library/postgres:${POSTGRESQL_VERSION:-16}"
    container_name: inmanta-db
    pull_policy: always
    environment:
      POSTGRES_USER: inmanta
      POSTGRES_PASSWORD: inmanta
    volumes:
      - inmanta-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inmanta"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  server:
    image: "${INMANTA_ORCHESTRATOR_IMAGE:?error}"
    container_name: inmanta-orchestrator
    pull_policy: always
    ports:
      - 127.0.0.1:8888:8888
    environment:
      INMANTA_DATABASE_HOST: inmanta-db
      INMANTA_DATABASE_USERNAME: inmanta
      INMANTA_DATABASE_PASSWORD: inmanta
    volumes:
      - inmanta-server-data:/var/lib/inmanta
      - inmanta-server-logs:/var/log/inmanta
    depends_on:
      db:
        condition: service_healthy

volumes:
  inmanta-db-data: {}
  inmanta-server-data: {}
  inmanta-server-logs: {}
