services:
  db:
    image: "docker.io/library/postgres:${POSTGRESQL_VERSION:-16}"
    container_name: inmanta-db
    pull_policy: always
    environment:
      POSTGRES_USER: inmanta
      POSTGRES_PASSWORD: inmanta
    volumes:
      - inmanta-db-data:/var/lib/postgresql/data
    command: "postgres -c jit=off"

  server:
    image: "${INMANTA_ORCHESTRATOR_IMAGE:-ghcr.io/inmanta/orchestrator:latest}"
    container_name: inmanta-orchestrator
    pull_policy: always
    ports:
      - "${INMANTA_ORCHESTRATOR_IP:-127.0.0.1}:${INMANTA_ORCHESTRATOR_PORT:-8888}:8888"
    environment:
      INMANTA_DATABASE_HOST: inmanta-db
      INMANTA_DATABASE_USERNAME: inmanta
      INMANTA_DATABASE_PASSWORD: inmanta
    volumes:
      - inmanta-server-data:/var/lib/inmanta
      - inmanta-server-logs:/var/log/inmanta

volumes:
  inmanta-db-data: {}
  inmanta-server-data: {}
  inmanta-server-logs: {}
