services:
  db-dump:
    image: "docker.io/library/postgres:${POSTGRESQL_VERSION:-16}"
    container_name: inmanta-db-dump-sidecar
    pull_policy: always
    entrypoint: ["/db-dump-entrypoint.sh"]
    environment:
      PGHOST: db
      PGUSER: inmanta
      PGDATABASE: inmanta
      PGPASSWORD: inmanta
    user: "root:root"
    healthcheck:
      test: ["CMD-SHELL", "if [ -f /var/lib/logrotate/status ]; then grep postgres /var/lib/logrotate/status; else which logrotate; fi"]
      interval: 5m
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./db-dump-entrypoint.sh:/db-dump-entrypoint.sh
      - ./db-dumps/:/var/lib/postgresql/data
      - inmanta-db-dump-data:/var/lib/logrotate

volumes:
  inmanta-db-dump-data: {}
