services:
  logrotate:
    image: "${INMANTA_ORCHESTRATOR_IMAGE:?error}"
    container_name: inmanta-logrotate-sidecar
    pull_policy: always
    entrypoint: ["/usr/bin/tini", "--", "/logrotate-entrypoint.sh"]
    user: "root:root"
    healthcheck:
      test: ["CMD-SHELL", "grep inmanta /var/lib/logrotate/status"]
      interval: 1h
      retries: 5
      start_period: 24h
      timeout: 10s
    volumes:
      - ./logrotate-entrypoint.sh:/logrotate-entrypoint.sh
      - inmanta-server-logs:/var/log/inmanta
      - inmanta-logrotate-data:/var/lib/logrotate

volumes:
  inmanta-logrotate-data: {}
